// Auto-generated by update_index.bat - DO NOT EDIT MANUALLY 
window.TERMINAL_DATA = { 
  credentials: { 
    "CODE01": "data" 
    ,"CODE02": "REBECCA" 
    ,"CODE03": "SCHMITZ" 
  }, 
  files: { 
    "data": [ 
        "NOTIFICATIONS.txt" 
        ,"test1.txt" 
        ,"welcome.txt" 
    ] 
    ,"REBECCA": [ 
        "NOTIFICATIONS.txt" 
        ,"sch.txt" 
    ] 
    ,"SCHMITZ": [ 
        "NOTIFICATIONS.txt" 
        ,"sch.txt" 
    ] 
  } 
}; 
